name: CI
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: ci
        run: npm ci

      - name: lint
        id: eslint
        continue-on-error: true
        run: npm run lint:report

      - name: Error Lint
        if: ${{ steps.eslint.outcome == 'failure' }}
        run: |
          run: |
               MSG="Se encontraron errores de lint. Se subirá el artifact eslint-report."
               echo "::warning title=Lint detectó errores::$MSG"
               echo "## Resultado de lint" >> "$GITHUB_STEP_SUMMARY"
               echo "" >> "$GITHUB_STEP_SUMMARY"
               echo "❌ $MSG" >> "$GITHUB_STEP_SUMMARY"

      - name: No error lint
        if: ${{ steps.eslint.outcome == 'success' }}
        run: |
          MSG="No se encontraron errores de lint."
          echo "::notice title=Lint sin errores::$MSG"
          echo "## Resumen de lint" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ $MSG" >> $GITHUB_STEP_SUMMARY

      - name: UploadEslintReport
        if: ${{ steps.eslint.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-report.txt

      - name: test
        run: npx ng test --watch=false

      - name: build
        run: npx ng build

      - name: Build docker image
        run: docker build -t angular-prueba:latest .
