name: CI
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: ci
        run: npm ci

      - name: lint
        id: eslint
        continue-on-error: true
        run: |
          npm run lint . -f stylish -o eslint-report.txt

      - name: Upload Eslint report
        if: ${{ steps.eslint.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: eslint-report.txt

      - name: test
        run: npx ng test --watch=false

      - name: build
        run: npx ng build

      - name: Build docker image
        run: docker build -t angular-prueba:latest .
